FROM 192.168.0.10:8080/kafka

WORKDIR /usr/bin
#RUN cd /app && rm -r *
COPY . /usr/bin
#RUN apk update && apk add py-pip && pip3 install Requests

EXPOSE 4000 9092

#CMD ["python3", "LR(Worker).py"]
#ENTRYPOINT [ "start.sh" ]
