FROM altariax0x01/controller

WORKDIR /app

COPY . /app
#RUN pip3 install --trusted-host pypi.python.org -r requirements.txt
#RUN apt-get -y install rsync ssh
#RUN apt-get -y install python3-pip
EXPOSE 4000 5000 22 873

ENV NAME ApatheticML

#ENTRYPOINT [ "sh ./start.sh" ]

